# Generated by Django 4.2.8 on 2024-01-19 06:39

from django.db import migrations, models
import one.users.utils


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Allowed file types:  png, jpg, jpeg.",
                null=True,
                upload_to=one.users.utils.user_directory_path,
                verbose_name="Avatar",
            ),
        ),
    ]
