# Generated by Django 4.2.8 on 2024-01-07 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("url", models.CharField(max_length=255, verbose_name="Bookmark url")),
                ("title", models.CharField(max_length=255, verbose_name="Bookmark title")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Belong to user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bookmark Menu",
                "verbose_name_plural": "Bookmark Menus",
                "ordering": ("id",),
            },
        ),
    ]
