# Generated by Django 4.2.8 on 2024-01-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmark",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Bookmark description"),
        ),
        migrations.AddField(
            model_name="bookmark",
            name="icon",
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name="Bookmark icon"),
        ),
    ]
