# Generated by Django 4.2.8 on 2024-01-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0002_bookmark_description_bookmark_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmark",
            name="description",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="Bookmark description"),
        ),
        migrations.AlterField(
            model_name="bookmark",
            name="icon",
            field=models.TextField(blank=True, default="", verbose_name="Bookmark icon"),
        ),
    ]
