# Generated by Django 4.2.8 on 2024-01-14 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardPreferences",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=100, verbose_name="Dashboard Code")),
                ("data", models.TextField(blank=True, null=True, verbose_name="Dashboard Data")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User dashboard preferences",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dashboard preference",
                "verbose_name_plural": "Dashboard preferences",
                "db_table": "dashboard_preferences",
                "ordering": ("user",),
                "unique_together": {("user", "code")},
            },
        ),
    ]
